### ISSUE TITLE
若干疑问处

### ISSUE THREAD

**Issue by ABCU** [fenixsoft/jvm_book#1]
Page238 :
  13:  iload_1 后的注释是否应该是字节码第14行的
Page259:
  13 astore_3 后注释Taget 是否为Target
Page265/266:
  作者注释1在266页出现两次，应该是排版问题
Page317:
  第五段第一句，Java语言在编译期间【却】已将。。。并作为。。。中的却是否改为【就】已将。。。并作为。。。更顺畅
Page312:
  代码实例中Father gay = new Son(); 中的gay 只是皮一下哈？

**Comment by fenixsoft** [comment]
十分感谢您的指正，5条均是书中错误，已更新至勘误。

第5条……真的是笔误，我笑到键盘都掉地上了。
