### ISSUE TITLE
P265被动引用例子之二

### ISSUE THREAD

**Issue by bluesmi** [fenixsoft/jvm_book#100]
您好，我使用oraclejdk1.8和11发现数组引用时，SuperClass还是加载了，请问这是什么原因呢？

[测试日志.txt](https://github.com/fenixsoft/jvm_book/files/5720428/default.txt)

**Comment by bluesmi** [comment]
但是SuperClass init!确实没有输出，只是没有看到“[Lorg.fenixsoft.classloading.SuperClass”这个类的初始化

**Comment by fenixsoft** [comment]
这个就是虚拟机实现的自由。被动引用那几个例子，讨论的是类什么情况下会或者不会进行初始化。在这部分开头就写到：

> 在什么情况下需要开始类加载过程的第一个阶段“加载”，《Java虚拟机规范》中并没有进行强制约束，这点可以交给虚拟机的具体实现来自由把握决定。但是对于初始化阶段，《Java虚拟机规范》则是严格规定了有且只有六种情况必须立即对类进行“初始化”（而加载、验证、准备自然需要在此之前开始）：

**Comment by bluesmi** [comment]
那请问，什么版本的虚拟机会出现您说的那种情况？

**Comment by fenixsoft** [comment]
> 那请问，什么版本的虚拟机会出现您说的那种情况？

哪种情况？

**Comment by bluesmi** [comment]
显示这个Lorg.fenixsoft.classloading.SuperClass日志的情况

**Comment by fenixsoft** [comment]
> 显示这个Lorg.fenixsoft.classloading.SuperClass日志的情况

日志我看了，但是我没看出来问题在哪里。你具体遇到了什么问题描述一下。

**Comment by bluesmi** [comment]
根据书中所表达的，日志中应该会出现加载Lorg.fenixsoft.classloading.SuperClass这个类的日志，但在我本机测试的情况来看，没有找到您说的Lorg.fenixsoft.classloading.SuperClass这个日志，询问您之后，是根据虚拟机的实现不同而显示的不同，所以我想问下您，您测试该例子的时候，使用的是什么样的环境，也就是说jdk版本、虚拟机的版本是什么样的？

**Comment by fenixsoft** [comment]
> 根据书中所表达的，日志中应该会出现加载Lorg.fenixsoft.classloading.SuperClass这个类的日志

书中三个“被动引用的例子”，都是用来解释被动引用不会触发初始化的。“初始化”和“加载”之间的联系是：如果进行了初始化，必定已经进行了加载，这是《JVMS》的强制约束。但如果没有进行初始化，那要或者不要进行加载，这就是虚拟机实现的自由。

书的表述中完全没有涉及到“`日志中应该会出现加载Lorg.fenixsoft.classloading.SuperClass这个类的日志`”的意思，如果有让读者容易产生误解的模糊之处，可以指出具体原文具体内容，以便我在重印时修正。

最后，从你给出的日志中，SuperClass这个类已经加载了。
`[Loaded com.github.jvm.chapter7.SuperClass from file:/Users/bluesmi/Documents/mycode/leetcode/build/classes/java/main/]`
上面所说的这三个例子，证明的是间接引用**未进行初始化**，因此该类加载或者未加载都是可以的，只是HotSpot虚拟机选择了进行加载而已。

**Comment by bluesmi** [comment]
好的，谢谢
