### ISSUE TITLE
p230脚注第二点的疑问

### ISSUE THREAD

**Issue by Belo-betty** [fenixsoft/jvm_book#101]
周老师您好，p230脚注第二点有个疑问

原文为：
Java代码的方法特征签名只包括方法名称、参数顺序及参数类型，
请问这里是不是少了“参数数量”，

参考p227最后一段第二行，
原文为：
方法的参数列表（包括数量、类型以及顺序）和返回值。

**Comment by fenixsoft** [comment]
感谢指正，已更新至勘误。
