### ISSUE TITLE
代码清单3-7 验证疑问

### ISSUE THREAD

**Issue by zhangshuge** [fenixsoft/jvm_book#102]
周老师好：针对第三版130页中的新生代Minor GC案例的测试代码进行了验证，无论我在Mac还是windows上，通过JDK1.8版本执行出来的结果，并不符合Eden占4M、survivor空闲、老年代占用6M的预期。请问这是什么原因？
Mac环境下打印结果：jdk1.8.0_271

>  Heap
 PSYoungGen      total 9216K, used 7896K [0x00000007bf600000, 0x00000007c0000000, 0x00000007c0000000)
  eden space 8192K, 96% used [0x00000007bf600000,0x00000007bfdb6010,0x00000007bfe00000)
  from space 1024K, 0% used [0x00000007bff00000,0x00000007bff00000,0x00000007c0000000)
  to   space 1024K, 0% used [0x00000007bfe00000,0x00000007bfe00000,0x00000007bff00000)
 ParOldGen       total 10240K, used 4096K [0x00000007bec00000, 0x00000007bf600000, 0x00000007bf600000)
  object space 10240K, 40% used [0x00000007bec00000,0x00000007bf000010,0x00000007bf600000)
 Metaspace       used 3080K, capacity 4496K, committed 4864K, reserved 1056768K
  class space    used 343K, capacity 388K, committed 512K, reserved 1048576K 

Windows环境见图片：
![image](https://user-images.githubusercontent.com/18241336/104795969-6814ee80-57ed-11eb-9e1a-89ac68c13f5d.png)

**Comment by zhangshuge** [comment]
我在idea中显示的增加了JVM参数-XX:+UseSerialGC之后，各区域的内存分配符合预期了。另外我发现 -XX:PretenureSizeThreshold=3m  这个参数可以直接写成3m而非必须填写字符大小。

**Comment by fenixsoft** [comment]
此问题解答过：https://github.com/fenixsoft/jvm_book/issues/55
