### ISSUE TITLE
Page89原始快照

### ISSUE THREAD

**Issue by Parker1995** [fenixsoft/jvm_book#107]
> 原文：当灰色对象要删除指向白色对象的引用关系时，就将这个要删除的引用记录下来，在并发扫描结束之后，再将这些记录过的引用关系中的灰色对象为根，重新扫描一次。

假设黑色对象A指向了灰色对象B，灰色对象B指向了白色对象C。并发标记阶段中，mutator将黑色对象A指向了白色对象C，同时删除了灰色对象B指向白色对象C的引用，就会导致白色对象C发生标记遗漏。

所以我们破坏它的第二条条件，不应该是将这个被删除的白色对象C列入SATB本地队列当中吗？如果是说将记录过的引用关系中的灰色对象为根，那不是等于没有破坏第二个条件了吗？

**Comment by gaochengyidlmu** [comment]
@Parker1995 我非常赞同你的观点，我认为是将白色对象标记为灰色，然后将其加入了重新扫描组
https://www.cnblogs.com/hongdada/p/14578950.html
