### ISSUE TITLE
3.4.3 安全区域

### ISSUE THREAD

**Issue by wuzhengdong1** [fenixsoft/jvm_book#114]
你好 想请教一个问题，书中说安全区域是为了解决在安全点的情况下，非活动线程不能响应中断的问题。那么在安全区域的情况下，没有进入安全区域的非活动线程是怎么处理的呀？是会等到重新分配CPU时间时，进入安全区域后再进行根节点枚举吗？

谢谢🙏

**Comment by fenixsoft** [comment]
答案取决于你这里的“非活动线程”定义是什么？
按照经典操作系统原理的表述，是指[五状态模型](https://en.wikipedia.org/wiki/Process_state)的就绪态（Waiting State，一切外部资源都准备好了，只是缺CPU时间）？还是指阻塞态（Blocked，缺执行所需的外部资源）？
书中提及的安全区域是针对阻塞态LWP的机制，安全点是针对运行态和就绪态LWP的机制。你的问题中“非活动线程”似乎指的是处于就绪态的LWP，那如果中断时不处于安全点的话，等到分配CPU时间，跑到最近的安全点即可。

**Comment by wuzhengdong1** [comment]
> 答案取决于你这里的“非活动线程”定义是什么？
> 按照经典操作系统原理的表述，是指[三状态模型](https://en.wikipedia.org/wiki/Process_state)的就绪态（Waiting State，一切外部资源都准备好了，只是缺CPU时间）？还是指阻塞态（Blocked，缺执行所需的外部资源）？
> 书中提及的安全区域是针对阻塞态LWP的机制，安全点是针对运行态和就绪态LWP的机制。你的问题中“非活动线程”似乎指的是处于就绪态的LWP，那如果中断时不处于安全点的话，等到分配CPU时间，跑到最近的安全点即可。

我说的非活动状态指的是线程处于阻塞态，书中说在安全点的情况下，线程处于阻塞态的时候，线程不能响应虚拟机的中断请求，并且虚拟机不能等到阻塞态的线程被重新分配CPU时间片再运行到安全点，所以引入了安全区域。我的问题是那些没有进入**安全区**并且处于阻塞态的线程虚拟机是怎么处理的？是等其分配到CPU时间片运行到安全区，再进行根节点枚举，还是不做处理？

**Comment by fenixsoft** [comment]
并不存在"那些没有进入安全区并且处于阻塞态的线程"。
进入Blocked状态与进入Waiting状态不同，Waiting是由操作系统调度的，什么时候被剥夺CPU时间不可控；但进入Blocked状态完全是由用户代码的自身操作所导致的结果，在进入Blocked前设置安全区即可。

**Comment by wuzhengdong1** [comment]
> 并不存在"那些没有进入安全区并且处于阻塞态的线程"。
> 进入Blocked状态与进入Waiting状态不同，Waiting是由操作系统调度的，什么时候被剥夺CPU时间不可控；但进入Blocked状态完全是由用户代码的自身操作所导致的结果，在进入Blocked前设置安全区即可。

嗯嗯 多谢哈🙏 还想问一下 那在安全点的时候，将进入Blocked状态的语句作为安全点，也就不会存在无法响应虚拟机中断请求，并且不能再走到安全点的地方中断挂起自己的线程了。那似乎好像也就不需要安全区域了？

**Comment by fenixsoft** [comment]
从代码来看是一条语句，但却很难视为一个点。其中的差别是安全点最终在机器一侧看到的通常只是一条用于轮询的test指令。但是让线程进入Blocked状态的操作通常无法直接插入这种指令，因为它往往是虚拟机提供的JNI方法来实现的，只能在进入这个方法的前后设置为安全区域。

**Comment by wuzhengdong1** [comment]
> 从代码来看是一条语句，但却很难视为一个点。其中的差别是安全点最终在机器一侧看到的通常只是一条用于轮询的test指令。但是让线程进入Blocked状态的操作通常无法直接插入这种指令，因为它往往是虚拟机提供的JNI方法来实现的，只能在进入这个方法的前后设置为安全区域。

好的 多谢解答🙏 辛苦
