### ISSUE TITLE
请教一个关于书上P265页由anewarray指令触发生成的新类问题？

### ISSUE THREAD

**Issue by Ant-dong** [fenixsoft/jvm_book#121]
<img width="1120" alt="QQ20210606-125543@2x" src="https://user-images.githubusercontent.com/33663400/120913060-d7b94680-c6c6-11eb-9b68-2d85e65dca98.png">
通过运行P265页的代码清单7-2，并没有发现有"[Lcom.frame.jvm.classinitical.SuperClass"被加载（书中说的是"[Lorg.fenixsoft.classloading.SuperClass"这个类 我本地就上前面的那个类），上图中只展示了一小部分日志截图，但是也查找了前面的日志也是没有发现这个类被加载，怎么知道这个类被初始化了？

**Comment by fenixsoft** [comment]
数组类不是从磁盘加载，而是有虚拟机内部自行产生的。，所以`-XX:+TraceClassLoading`不显示，确实并没有什么好的方法从外部去观察。
所以这个问题只能从理论上，根据JVMS的_5.3.3 Creating Array Classes_去回答，或者聚焦到具体的虚拟机实现上，譬如跟踪HotSpot的源码去确认。

**Comment by Ant-dong** [comment]
好的 知道了多谢
