### ISSUE TITLE
P178 第6条汇编代码解读疑惑

### ISSUE THREAD

**Issue by frichris** [fenixsoft/jvm_book#122]
第6条“取类变量b，这次是访问方法区中的数据”，变量b作为类Bar的静态变量，是不是应该和Class对象一起存放在Java堆上，而不是方法区中？
或者更严谨点，JDK7之前的版本是访问方法区中的数据，JDK7及其以后版本是访问Java堆。
（P156 也提到“JDK7及其以后版本的HotSpot虚拟机选择将静态变量与类型在Java语言一端的映射Class对象存放在一起，存储在Java堆之中”）

**Comment by fenixsoft** [comment]
这个其实很多人都掉进去过的trap。

《JVMS》中定义了heap和method area两个**逻辑概念**。并明确了per-class级别的数据应存放在method area中，per-object级别的数据应存放在heap中。
> 2.5.3 Heap
> Heap storage for objects is reclaimed by an automatic storage management system
> 
> 2.5.4 Method Area：
> Method area stores per-class structures such as the run-time constant pool, field and method data, and the code for methods and constructors

在实现具体的Java虚拟机时，具体用什么**物理方法**去实现heap和method area这两个逻辑概念，是虚拟机开发者的自由。
HotSpot选择了使用javaheap去实现heap，使用perm gen（jdk7-）、metaspace及部分的javaheap（jdk8+)去实现method area。这自然是可行且合理的，并不是意味着其中由javaheap去存放的那部分数据就不再属于method area了。

我举个不太恰当的比喻供你参考：

假设我定义了`黄种人`指代所有换皮肤的人类，`白种人`指代所有白皮肤的人类。如果有一名韩国人，从韩国本移民到了美国，在实际的物理身份上，它确实是从韩国人变成了美国人，但是并不影响他仍然是归属于`黄种人`这个逻辑概念范畴之中。同理，即使目前HoSpot选择将class field存放到javaheap之中，也不会改变field仍然是一种per-class structures，应归属于method area的范畴之中。

**Comment by frichris** [comment]
感谢解惑！逻辑概念和具体实现的区别在书中已有说明，是我看着看着给忘了...
