### ISSUE TITLE
勘误修正的内容，是否有计划同步更新电子版？

### ISSUE THREAD

**Issue by JimmyLincole** [fenixsoft/jvm_book#126]
老师好，请问勘误修正后的内容，是否有计划同步更新电子版？比如“京东读书”。
谢谢老师！

**Comment by fenixsoft** [comment]
这件事情我做不了，要由出版社和各个电子版APP去协作完成。
据我观察，微信图书上的仍然是最初版本，没有合并过勘误的内容。
