### ISSUE TITLE
示例代码类名typo : SynAddRunalbe -> SynAddRunnable

### ISSUE THREAD

**Issue by XenoAmess** [fenixsoft/jvm_book#137]
![MVIMG_20210922_164851](https://user-images.githubusercontent.com/17455337/134314682-5d94639a-e17d-4018-ab2b-8fc24b8b3db3.jpg)

如图

按照人类语义，图中的类应命名为`SynAddRunnable`,而不是`SynAddRunalbe`。

(虽然个人认为这个类或许叫SynchronizedAddingRunnable会更加合适)

但是至少请把这个typo修了

**Comment by fenixsoft** [comment]
这个typo在一年前勘误# 4-14中已经修过。
另电子版未能更新的也已解释过 #126。

**Comment by XenoAmess** [comment]
那你这个仓库里的示例代码 同步下啊。。

**Comment by XenoAmess** [comment]
src目录下的那些

**Comment by XenoAmess** [comment]
fixed by https://github.com/fenixsoft/jvm_book/commit/54c165d7bbb65dcb9018d31d41ba1d76e2020a86
