### ISSUE TITLE
第一章1.6节提到的CMakeLists.txt已经无法下载了

### ISSUE THREAD

**Issue by lijian12345** [fenixsoft/jvm_book#19]
书中地址为https://github.com/ojdkbuild/ojdkbuild/blob/master/src/java-12-openjdk/CMakeLists.txt

目前这个仓库里已没有jdk12的CMakeLists.txt，只有8,11,13的。

**Comment by fenixsoft** [comment]
hmmm……GitHub不是网盘，从History中翻出来便是。

https://github.com/ojdkbuild/ojdkbuild/blob/8501f54c971c3fe2623bd9faee85ff6c2431d0de/src/java-12-openjdk/CMakeLists.txt

**Comment by lijian12345** [comment]
> hmmm……GitHub不是网盘，从History中翻出来便是。
> 
> https://github.com/ojdkbuild/ojdkbuild/blob/8501f54c971c3fe2623bd9faee85ff6c2431d0de/src/java-12-openjdk/CMakeLists.txt

多谢多谢2333
