### ISSUE TITLE
若干疑问处2

### ISSUE THREAD

**Issue by ABCU** [fenixsoft/jvm_book#2]
Page254 :
  算术指令用于对两个操作数栈上的值进行。。。 此处是否改为【对操作栈上的两个值进行】略为不容易歧义，初读此处不了解操作栈，根据后文内容发现自己前文理解错误。
Page322:
  作者注释的INDY链接博文还存在，但托管工具代码的Kenai.com站点已关闭，已无法获取相关工具;作者本地还有备份的话方便在仓库中共享一下？
Page348:
   9.3节 第一段最后一句，【通常解决类问题有以下几种途径：】类字前是否欠缺【该】、【这】、【此】等字眼
Page372:
  正文第二段第二行：譬如将代码清单【10-2】稍微修改，此处的10-2 实为10-4
Page396:
  正文第二段第一句中：图11-2 和图11-3 应该是 图11-3 和图11-4

**Comment by fenixsoft** [comment]
已经全部添加至勘误中。
衷心感谢您的多次反馈。
