### ISSUE TITLE
p456 12.4 java与线程

### ISSUE THREAD

**Issue by suiyueyu** [fenixsoft/jvm_book#28]
p456在介绍`2.用户线程实现`时，书中这样写道

> 这种进程与用户线程之间 1:N 的关系称为一对多的线程模型

这里是不是应该是 (内核)**线**程和用户线程之间的 1:N，这样才和之前`1. 内核线程实现`一节中提到的

> 轻量级进程与内核进程之间1:1的关系

逻辑上一致，`1:1`, `1:N`, `N:M` 三种关系

感谢。

**Comment by fenixsoft** [comment]
你好。
这里的逻辑关系确实不是直接等价的，即1:N说的“Process ：UserThread”和1:1中说的”Light Weight Process：Kernel Level Thread”不是直接对等。
放在12.4.1.2中描述的1:N实现，在时间顺序上要比12.4.1.1中描述的1:1实现出现得更早，囿于语言理解的习惯把才它放到了第2节。
后续介绍协程时简单提到过，早期的一些操作系统，是没有调度器、内核线程这些基础设施的（这是用户线程被发明和发展的背景），由于此时根本不存在“内核线程”，所以这里1:N中1的对象只能是进程，这点也在图中有所体现（图12-4中P和UT的关系）。
不过，在现代操作系统和带有用户线程的语言中，你问题中所描述的理解是正确的，无论是Java的Project Loom、Kotlin的Coroutine，或者是Go、Erlang等，用户线程最终都是会被映射到内核线程上。

**Comment by suiyueyu** [comment]
感谢回答，我还以为是笔误...
