### ISSUE TITLE
勘误：7.3.5 小节

### ISSUE THREAD

**Issue by ZZKdev** [fenixsoft/jvm_book#29]
在 7.3.5 小节中（初始化），有一个例子用来证明父类静态代码块要先于子类中运行中提到：
> 由于父类的\<clinit\>()方法先执行，也就意味着父类中定义的静态语句块要优先与子类的变量赋值，如代码清单7-6中，**字段B的值将会是2而不是1**。

这里应该是：字段B的值将会是2而不是0。
因为如果子类变量的赋值（\<clinit\>方法）先执行的话，此时父类的静态代码块 （\<clinit\>() 方法）还未执行，字段 A 的值应该还为 0 ？
感觉代码清单的例子来证明不太好，字段 A 的赋值有点多余...，反正最后都是收集成 \<clinit\> 方法，putstatic 两次。删掉 A 字段的赋值会清晰很多,换成
```
static class Parent{
    public static int A;
    static {
        A = 2;
    }
}
```

**Comment by fenixsoft** [comment]
只要有“反正最后都是收集成 <clinit> 方法”的认知就不会出问题。这里在父类、子类都安排了赋值操作，是为了预防以下这种**不正确**的执行顺序理解：

> 1. 执行父类类变量赋值
> 2. 执行子类类变量赋值
> 3. 执行父类static {}块
> 4. 执行子类static {}块

**Comment by ZZKdev** [comment]
还是大大想得周到 >_<
