### ISSUE TITLE
勘误：P501 的 pop2 指令问题

### ISSUE THREAD

**Issue by gldwolf** [fenixsoft/jvm_book#34]
您好，P501 的那 `pop2` 的指令含义是不是写反了呢，原书内容是：`将栈顶的一个（对于 long 或 double 类型）或两个数值（对于非 long 或 double 类型）弹出`，请问是不是应该是 `将栈顶的一个（对于非 long 或 double 类型）或两个数值（对于 long 或 double 类型）弹出` ？：）

**Comment by fenixsoft** [comment]
根据[JVMS](https://docs.oracle.com/javase/specs/jvms/se8/jvms8.pdf)的规定：

> **pop2**
> Pop the top one or two operand stack values
> ..., value2, value1 →  ...
> where each of value1 and value2 is a value of a category 1 computational type (§2.11.1).
> ..., value → ...
> where value is a value of a category 2 computational type (§2.11.1).

§2.11.1 long和double是category 2，其余类型是category 1

出栈1个long或double，出栈2个其他类型，没有问题鸭

**Comment by gldwolf** [comment]
哈哈，不好意思啊，是我理解不到位 :(
