### ISSUE TITLE
Page 57: 两处"异常出现时输出的堆栈深度相应缩小" 的问题

### ISSUE THREAD

**Issue by newryu** [fenixsoft/jvm_book#36]
不理解"相应缩小"是什么意思. 这里会不会写错了? 是不是"异常出现时输出堆栈深度相应大小"?

**Comment by fenixsoft** [comment]
"相应缩小"就是“减少栈容量/扩大本地变量表后，代码输出的栈深度相应地减小了”。从语文的角度这个应该不算问题。

**Comment by newryu** [comment]
> "相应缩小"就是“减少栈容量/扩大本地变量表后，代码输出的栈深度相应地减小了”。从语文的角度这个应该不算问题。

明白了，感谢解答！
