### ISSUE TITLE
勘误：Page 280 代码清单7-8

### ISSUE THREAD

**Issue by wangqianyang** [fenixsoft/jvm_book#37]
应该Override ClassLoader的findClass方法，不是loadClass方法

**Comment by fenixsoft** [comment]
能具体说一下吗？
重写findClass就被委派到父类加载器加载了，这时候输出的结果是true，达不到返回false的目的。

**Comment by wangqianyang** [comment]
p285页您已经说明了，双亲委派的逻辑在loadClass()方法中，如果父类加载失败，就会调用字节的findClass()方法来完成加载，这样既保证了双亲委派的规则，又实现了按照自己的意愿加载类。JDK1.2之后添加了findClass()方法，已经不允许loadClass()方法的重写了。
实际代码run一下的话，重写loadClass()报错。

以上，请您复核一下

**Comment by fenixsoft** [comment]
> **Page 285原文**
> Java设计者们引入双亲委派模型时不得不做出一些妥协，为了兼容这些已有代码，无法再以技术手段避免loadClass()被子类覆盖的可能性，只能在JDK 1.2之后的java.lang.ClassLoader中添加一个新的protected方法findClass()，并引导用户编写的类加载逻辑时尽可能去重写这个方法，而不是在loadClass()中编写代码。

以上并没有表达不允许重写loadClass方法的意思。如果直接禁止重写这个方法，以前很多遗留代码就会出现问题。

关于运行报错，我试了下，并没有出现问题，请把具体报错信息贴一下：

``` bash
# root @ IcyFenix-PC in /mnt/d/develop/jvm_book/src
$ cat org/fenixsoft/jvm/chapter7/ClassLoaderTest.java 
package org.fenixsoft.jvm.chapter7;

/**
 * @author zzm
 */

import java.io.IOException;
import java.io.InputStream;

/**
 * 类加载器与instanceof关键字演示
 *
 * @author zzm
 */
public class ClassLoaderTest {

    public static void main(String[] args) throws Exception {

        ClassLoader myLoader = new ClassLoader() {
            @Override
            public Class<?> loadClass(String name) throws ClassNotFoundException {
                try {
                    String fileName = name.substring(name.lastIndexOf(".") + 1) + ".class";
                    InputStream is = getClass().getResourceAsStream(fileName);
                    if (is == null) {
                        return super.loadClass(name);
                    }
                    byte[] b = new byte[is.available()];
                    is.read(b);
                    return defineClass(name, b, 0, b.length);
                } catch (IOException e) {
                    throw new ClassNotFoundException(name);
                }
            }
        };

        Object obj = myLoader.loadClass("org.fenixsoft.jvm.chapter7.ClassLoaderTest").newInstance();

        System.out.println(obj.getClass());
        System.out.println(obj instanceof org.fenixsoft.jvm.chapter7.ClassLoaderTest);
    }
}

# root @ IcyFenix-PC in /mnt/d/develop/jvm_book/src
$ java -version
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+10)
OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)

# root @ IcyFenix-PC in /mnt/d/develop/jvm_book/src
$ javac org/fenixsoft/jvm/chapter7/ClassLoaderTest.java 

# root @ IcyFenix-PC in /mnt/d/develop/jvm_book/src
$ java org.fenixsoft.jvm.chapter7.ClassLoaderTest
class org.fenixsoft.jvm.chapter7.ClassLoaderTest
false
```

**Comment by wangqianyang** [comment]
我刚运行了您的代码，确实没有问题，我的代码结构确实和您的也不一样，但是我不太清楚差异在哪，我贴一下，我的JDK是1.8

`
package com.example.demo.service.jvm;
import java.io.IOException;
import java.io.InputStream;

public class ClassLoaderTest {

    public static ClassLoader getClassLoader() {

        ClassLoader classLoader = new ClassLoader() {
            @Override
            public Class<?> loadClass(String name) throws ClassNotFoundException {
                //return super.loadClass(name);
                String fileName = name.substring(name.lastIndexOf(".") + 1) + ".class";
                InputStream is = getClass().getResourceAsStream(fileName);
                if (is == null) {
                    super.loadClass(name);
                } else {
                    try {
                        byte[] b = new byte[is.available()];
                        is.read(b);
                        return defineClass(name, b, 0, b.length);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
                return null;
            }
        };
        return classLoader;
    }

    public static void main(String[] args) {
        Object obj = null;
        try {
            obj = getClassLoader().loadClass("com.example.demo.service.jvm.ClassLoaderTest").newInstance();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        System.out.println(obj.getClass());
        System.out.println(obj instanceof ClassInitTest);
    }
}
`
报错信息：
`
Exception in thread "main" java.lang.NoClassDefFoundError: java/lang/Object
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.example.demo.service.jvm.ClassLoaderTest$1.loadClass(ClassLoaderTest.java:22)
	at com.example.demo.service.jvm.ClassLoaderTest.main(ClassLoaderTest.java:36)
`

**Comment by fenixsoft** [comment]
Object是依赖bootstrap classloader加载的，你代码中直接把加载的返回值给丢弃了。

``` java
if (is == null) {
    super.loadClass(name);  // ===> return super.loadClass(name);
} 
```

**Comment by wangqianyang** [comment]
感谢大佬的指点，确实是丢失返回值的原因，我的问题，这个勘误可以取消了
