### ISSUE TITLE
Page 78: 图 3-2 和 图 3-3 的问题

### ISSUE THREAD

**Issue by newryu** [fenixsoft/jvm_book#41]
Page 78: 图 3-2 回收后状态 2行2列和3行2列 这两格在书中是白色的未使用, 是否应该改为存活对象的颜色?
图 3-3 回收后状态 2行6、7、8列 这三格在书中是白色的未使用, 是否应该改为存活对象的颜色?

**Comment by fenixsoft** [comment]
谢谢，已更新到勘误。
查了一下原稿，原稿是对的，我去请编辑接锅。

**Comment by zjxjwxk** [comment]
补充：图 3-3 回收前状态的 3 行 4 列应该也为可回收？作者的意思应该是这两张图的回收前状态一样吧？这样图 3-3 回收后状态的存活数量对象就对了。
