### ISSUE TITLE
Page 235 疑问

### ISSUE THREAD

**Issue by Kyrie-yx-Irving** [fenixsoft/jvm_book#60]
原书第三版第235页：
> 2）读入B7， 查表得0xB7对应的指令为invokespecial， 这条指令的作用是以栈顶的reference类型的数据所指向的对象作为方法接收者， 调用此对象的实例构造器方法、 private方法或者它的父类的方法。 这个方法有一个u2类型的参数说明具体调用哪一个方法， 它指向常量池中的一个 CONSTANT_Methodref_info类型常量， 即此方法的符号引用。
> 3）读入 00 0A， 这是invokespecial指令的参数，代表一个符号引用，查常量池得0x000A的对应常量为实例构造器"<init>()"方法的引用。

我查询了代码清单的6-2的常量池：
```
Constant pool:
   #1 = Class              #2             // test/TestClass
   #2 = Utf8               test/TestClass
   #3 = Class              #4             // java/lang/Object
   #4 = Utf8               java/lang/Object
   #5 = Utf8               m
   #6 = Utf8               I
   #7 = Utf8               <init>
   #8 = Utf8               ()V
   #9 = Utf8               Code
  #10 = Methodref          #3.#11         // java/lang/Object."<init>":()V
  #11 = NameAndType        #7:#8          // "<init>":()V 
```
0x000A也就是十进制的10， 也就是指`#10`常量， `#3.#11`的意思(通过后面的注释可知)，是`java/lanObject."<init>":()V`, 我理解为这是`Object`的构造器方法引用， 也就是说父类的构造器方法的引用(我理解为上文中第二点的父类的方法)， 而文中说的却是实例构造器的`<init>()`方法引用， 两者应该不同吧？ 是我哪里理解错了吗？

**Comment by fenixsoft** [comment]
”实例构造器“的意思并不是”该对象实例或者Object的构造器“。”实例构造器“（instance initialization method）是一个完整的名词，定义在《JVMS》的2.9 Special Methods中，不能拆成”某个实例“的”构造器“来理解。

> At the level of the Java virtual machine, every constructor written in the Java programming language (JLS §8.8) appears as an **instance initialization method** that has the special name <init>

因此"查常量池得0x000A的对应常量为实例构造器\<init\>()方法"这句话，并不是说某个实例（而非父类Object）的意思的构造器的意思。指的就是0x000A对应了一个\<init\>()方法

**Comment by Kyrie-yx-Irving** [comment]
好的，谢谢作者解惑！
