### ISSUE TITLE
关于「第五次重印版修正勘误」的勘误

### ISSUE THREAD

**Issue by super9du** [fenixsoft/jvm_book#72]
## 勘误更正 5.1

原勘误为：

> Page 94：-XX:GCTimeRatio参数的值则应当是一个大于0小于100的整数，也就是垃圾收集时间占总时间的比率，【相当于是吞吐量的倒数】。
更正：-XX:GCTimeRatio参数的值则应当是一个大于0小于100的整数，也就是垃圾收集时间占总时间的比率，【这个参数设定为N的话，表示用户代码执行时间与总执行时间之比为N：N+1】

建议改为：

>  `-XX:GCTimeRatio` 用于表示GC执行用时与用户代码执行用时之比。譬如 `-XX:GCTimeRatio=99` 指的就是 `GC执行用时 : 用户代码执行用时 = 1 : 99`，即 GC 执行用时占 JVM 执行总用时的 1% （GC 执行用时所占比例 = GC执行用时/(1+用户代码执行总用时)=1/(1+99)=1%）。

另外建议可以在此处加上脚注：
> 在 JVM 的参数中，假设有 `-XX:{FlagName}Ratio=otherValue` ，则表示名为 FlagName 的内容与其他内容的比值为 `1 : otherValue`。譬如 `-XX:SurvivorRatio=8` 表示 Survivor 与 Eden 内存空间之比为 `1 : 8`，由于 Survivor 区有两个，所以 Survivor 区占新生代总内存的 1/5。又譬如 `-XX:NewRatio=2` 表示新生代与老年代的内存空间之比为 `1 : 2`，所以新生代占堆总内存的 1/3。

**关于「-XX:GCTimeRatio参数的值则应当是一个大于0小于100的整数」的勘误**

我对原勘误（和原文）中「-XX:GCTimeRatio参数的值则应当是一个大于0小于100的整数」这句话中参数值为「0-100」这个数据表示质疑。经验证，原勘误（或原文）中内容有误。我使用了Windows10 + JDK8的环境，执行了如下命令：

```
C:\Users\Xxx>java -XX:+PrintFlagsFinal -version|findstr GCTimeRatio
uintx GCTimeRatio                               = 99                                  {product}
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)   

C:\Users\Xxx>java -XX:GCTimeRatio=0 -XX:+PrintFlagsFinal -version|findstr GCTimeRatio
uintx GCTimeRatio                              := 0                                   {product}
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode) 

C:\Users\Xxx>java -XX:GCTimeRatio=101 -XX:+PrintFlagsFinal -version|findstr GCTimeRatio
uintx GCTimeRatio                              := 101                                 {product}
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode) 

C:\Users\Xxx>java -XX:GCTimeRatio=-1 -XX:+PrintFlagsFinal -version|findstr GCTimeRatio
Improperly specified VM option 'GCTimeRatio=-1'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

`-XX:+PrintFlagsFinal` 表示打印最终参数值。根据执行的第一条命令可以看出，该值默认为99；第二条命令显示该值可以为0；第三条命令显示该值可以为101；第四条显示该值如果不符合范围会报错（但也可能是因为由于是不符合无符号整数的要求）。经过我使用可执行 jar 做测试后发现，该值设置为 0 和 101 均可使用，也印证了以上结论。

最后我对 `-XX:GCTimeRatio=0` 依然可以执行感到了迷惑……

## 勘误更正 5.2

原勘误为：
> Page 392：脚注：是诸多跑分软件的测试【用力】通常都属于第二种，如果不去支持跑分会显得成绩很不好看。
更正：是诸多跑分软件的测试【用例】通常都属于第二种，如果不去支持跑分会显得成绩很不好看。

原文为：
> ......的【理由，是】诸多跑分软件的测试【用力】......

建议改为：
> .....的【理由是：】诸多跑分软件的测试【用例】......

## 勘误更正 5.3

原勘误为：
> Page 480：对一些代码要求同步，但是【对被检测】到不可能存在共享数据竞争的锁进行消除
更正：对一些代码要求同步，但是【虚拟机又检测】到不可能存在共享数据竞争的锁进行消除

原文为（增加了前后文，以方便理解）：
> 锁消除是指虚拟机即时编译器在运行时【，对一些代码要求同步，但是对被检测到】不可能存在共享数据竞争【的锁进行消除】。

建议改为：
> 锁消除是指虚拟机即时编译器在运行时【检测到某段需要同步的代码】不可能存在共享数据竞争【而实施的一种对锁进行消除的优化策略】。

**Comment by fenixsoft** [comment]
感谢指正。

首先，关于原文中0-100的问题，**原文是错误的**，GCTimeRatio只需要是一个unit类型的整数即可，并没有范围的限定。

其次，关于这GCTimeRatio的描述，由于已经改过一遍，这次修改慎重一些，选择直接按照[Oracle官方资料](https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gc-ergonomics.html)中的解释方式：
> -XX:GCTimeRatio=nnn：A hint to the virtual machine that it's desirable that not more than 1 / (1 + nnn) of the application execution time be spent in the collector. By default the value is 99, meaning the application should get at least 99 times as much time as the collector. That is, the collector should run for not more than 1% of the total time.

修正为：
> -XX:GCTimeRatio参数的值应为设置为一个正整数，表示用户期望虚拟机消耗在GC上的时间不超过程序运行时间的1/(1+N）。默认值为99，含义是尽可能保证应用程序执行的时间为收集器执行时间的99倍，也即是收集器的时间消耗不超过总运行时间的1%。

最后，关于`-XX:GCTimeRatio=0`可以运行的问题，这个取决于不同收集器的AdaptiveSizePolicy是如何实现的，譬如PS是允许这样设置，后果就是每次GC都会进入到动态调整各分代大小的逻辑中。而G1就不允许这样设置，会自动调用set_g1_gc_flags()来覆盖。你可以尝试加上+XX:+UserG1GC看看。

**Comment by fenixsoft** [comment]
后面两个问题，你的建议均是合理的，已经更新到勘误。再次感谢！
