### ISSUE TITLE
第五版勘误修正内容的疑问

### ISSUE THREAD

**Issue by super9du** [fenixsoft/jvm_book#73]
题为「以下勘误内容已在第5次重印版（2020-9-11日）修正」的内容中：

> Page 128：JDK 9之前虚拟机运行在Server模式下的默认值，打开此开关后，使用【Parallel Scavenge + Serial Old（PS MarkSweep）的】收集器组合进行内存回收
更正：JDK 9之前虚拟机运行在Server模式下的默认值，打开此开关后，使用【Parallel】收集器组合进行内存回收

请问「使用【Parallel】收集器组合进行内存回收」中，修改为「Parrallel」的原因是什么呢？感觉更正前更容易让人理解呀。

**Comment by WWWWWWWXQ** [comment]
建议可以看一下issue#15 那是第一个提出来的

**Comment by super9du** [comment]
> 建议可以看一下 issue#15 那是第一个提出来的

谢谢，看到了。
