### ISSUE TITLE
关于本项目 README 中勘误内容的建议

### ISSUE THREAD

**Issue by super9du** [fenixsoft/jvm_book#74]
修正勘误应该有一个编号，以方便直接对某个勘误进行指认和沟通。

比如：

> **勘误 1001**，Page 70
原文：在虚拟机栈（栈帧中的本地变量表）中引用的对象，譬如【各个线程被调用的方法堆栈中使用到的参数、局部变量、临时变量等】
有同学反应太过拗口，修改为：在虚拟机栈（栈帧中的本地变量表）中的引用的对象，譬如【当前正在运行的方法所使用到的参数、局部变量、临时变量等】

**Comment by fenixsoft** [comment]
感谢，很合理的建议。
已经处理：对所有已经印刷的勘误都加入了编号；对还未刊印的，由于会随着新勘误产生页码改变，这部分等印刷后编号。
