### ISSUE TITLE
3th Edition P290 用在 IntelliJ IDE、Eclipse 这些 IDE 上做 HotSwap 倒是非常的合适

### ISSUE THREAD

**Issue by moqimoqidea** [fenixsoft/jvm_book#76]
周老师好：

我觉得书中关于 IntelliJ IDE 使用 HotSwap 进行功能加强可以做一些引用，Eclipse 这方面的资料我不太了解，就由其他同学提供了。例如下面三个链接，前两个是 JetBrains 官方链接，第三个是我之前的总结，希望作为参考有所帮助。

1. [HotSwap﻿](https://www.jetbrains.com/help/idea/debugger-hotswap.html)
2. [Alter the program's execution flow](https://www.jetbrains.com/help/idea/altering-the-program-s-execution-flow.html)
3. [IDEA - Debugger 经验总结](https://moqimoqidea.github.io/2017/06/02/IDEA-Debugger/)

**Comment by fenixsoft** [comment]
谢谢。
另，页数是P290。
