### ISSUE TITLE
Parallel Scavenge 是标记复制还是标记整理

### ISSUE THREAD

**Issue by LeewayHsu** [fenixsoft/jvm_book#9]
作者你好，书中P80页倒数第4行提到：”HopSpot 虚拟机里面关注吞吐量的 Parallel Scavenge 收集器是基于标记-整理算法的“。

而P93页3.5.3节提到：”Parallel Scavenge 收集器也是一款新生代收集器，它同样是基于标记-复制算法实现的收集器“。

所以它到底是标记复制还是标记整理呢？

**Comment by fenixsoft** [comment]
抱歉，80页那里是笔误，已更新至勘误，感谢提醒指正。已更正为:

> HotSpot虚拟机里面关注吞吐量的Parallel 【Old】收集器是基于标记-整理算法的

Parallel Scavenge是新生代收集器，新生代中的对象大多短命，所以几乎所有的新生代收集器都是基于标记-复制算法实现的。
Parallel Old是老年代收集器，老年代对象存活概率高，一般不采用复制算法。PS Old是基于标记-整理算法的收集器。
80页那里的上下文语境是拿它与另一款老年代收集器CMS进行对比，笔误写成了Parallel Scavenge。

**Comment by LeewayHsu** [comment]
好的，非常感谢。
