### ISSUE TITLE
第三版【2.4.3】 centos6.9 openjdk1.6 使用书中代码与jvm参数无法造成常量池溢出

### ISSUE THREAD

**Issue by suddenlyToday** [fenixsoft/jvm_book#91]
![image](https://user-images.githubusercontent.com/9245695/99087911-4721f880-2606-11eb-89ee-45b325981301.png)

不知道为何，我检查了几遍代码，应该没有敲错，即使把short改成long，也没有触发oom。

请作者帮忙看一下我哪里做错了吗？

**Comment by suddenlyToday** [comment]
希望作者能在百忙中抽空看一眼

**Comment by fenixsoft** [comment]
我试了一下，并没有发现什么问题。我的环境是Win10 WSL2 with ubuntu 18.04，跑windows版的jdk 6u45。
代码就是本repo的，将short改long。建议你用jconsole等工具观察一下perm gen的变化情况。

```
# root @ IcyFenix-PC in /mnt/d/develop/jvm_book/src [12:43:17]
$ /mnt/d/develop/Java/jdk1.6.0_45/bin/javac.exe org/fenixsoft/jvm/chapter2/RuntimeConstantPoolOOM_1.java

# root @ IcyFenix-PC in /mnt/d/develop/jvm_book/src [12:43:24] 
$ /mnt/d/develop/Java/jdk1.6.0_45/bin/java.exe org/fenixsoft/jvm/chapter2/RuntimeConstantPoolOOM_1 -XX:PermSize=6M -XX:MaxPermSize=6M
Exception in thread "main" java.lang.OutOfMemoryError: PermGen space
        at java.lang.String.intern(Native Method)
        at org.fenixsoft.jvm.chapter2.RuntimeConstantPoolOOM_1.main(RuntimeConstantPoolOOM_1.java:19)

# root @ IcyFenix-PC in /mnt/d/develop/jvm_book/src [12:43:51] C:1
$ cat org/fenixsoft/jvm/chapter2/RuntimeConstantPoolOOM_1.java
package org.fenixsoft.jvm.chapter2;

import java.util.HashSet;
import java.util.Set;

/**
 * VM Args：-XX:PermSize=6M -XX:MaxPermSize=6M
 *
 * @author zzm
 */
public class RuntimeConstantPoolOOM_1 {

    public static void main(String[] args) {
        // 使用Set保持着常量池引用，避免Full GC回收常量池行为
        Set<String> set = new HashSet<String>();
        // 在short范围内足以让6MB的PermSize产生OOM了
        long i = 0;
        while (true) {
            set.add(String.valueOf(i++).intern());
        }
    }
}
```

**Comment by suddenlyToday** [comment]
感谢作者的答复。

同样的代码我后来使用了oracle jdk1.6测试了确实是ok的。

但使用open jdk1.6确实触发不了oom，google了一下，说是openjdk1.6是openjdk1.7改过去的，所以它的常量池应该是在堆中。

于是使用Xmx参数限制堆大小试了一下，似乎确实如此。

![image](https://user-images.githubusercontent.com/9245695/99146612-b3f3cc00-26b4-11eb-8c80-a3ce47190d3a.png)

**Comment by fenixsoft** [comment]
OpenJDK 6确实是从OpenJDK 7中Backport而来，Sun建立OpenJDK项目就是以7的源码为基础的。具体可以参考一下书30页介绍的OpenJDK 6和OpenJDK 7的版本血源关系。

**Comment by suddenlyToday** [comment]
补充一下，2.4.2中使用cglib构造方法区oom，我测试时需要使用cglib的3.2.6-3.2.12版本才可，3.2.6之前的版本的setUserCache(false)有点问题，3.3.0版本只能用于jdk1.8以上版本。

**Comment by suddenlyToday** [comment]
![image](https://user-images.githubusercontent.com/9245695/99465812-17605100-2976-11eb-973d-e51b4cc8dafa.png)
![image](https://user-images.githubusercontent.com/9245695/99466131-cf8df980-2976-11eb-8b31-c6b58d544a6e.png)

另外发现一处代码问题，不知是否作者与我测试版本不同。
【2.4.4】中的直接内存oom测试在windows上会报oom，但那跟设置的-XX:MaxDirectMemorySize=10M没有关系，是因为到达了操作系统的内存上限；在mac和centos上则会直接因占内存过多而被killed。
经过测试发现，Unsafe.allocateMemory会绕过XX:MaxDirectMemorySIze的检查，而使用ByteBuffer.allocateDirect则可以直接触发XX:MaxDirectMemorySize上限而OOM。

另外，如果将ByteBuffer.allocateDirect放在while循环里1M1M的去allocate，也触发不了OOM。

**Comment by fenixsoft** [comment]
> 补充一下，2.4.3中使用cglib构造方法区oom，我测试时需要使用cglib的3.2.6-3.2.12版本才可，3.2.6之前的版本的setUserCache(false)有点问题，3.3.0版本只能用于jdk1.8以上版本。

repo中带的cglib是2.2.2。
关于只有“3.2.6-.3.2.12版本才可以”的问题，具体是指？

可以参考一下是否与这个issues中提到的问题相同？
https://github.com/fenixsoft/jvm_book/issues/45

**Comment by fenixsoft** [comment]
关于DirectMemory的问题之前回复过，供你参考：https://github.com/fenixsoft/jvm_book/issues/16

这个例子确实举得不好，下一次改版（指第4版，勘误为维持页数统一不能做大的变动）我会替换掉这个例子。

**Comment by suddenlyToday** [comment]
2.x的cglib没有尝试，只试了3.x的，我在mac上测试使用3.2.1到3.2.5的没有触发oom，使用3.2.6以后的都ok。

**Comment by suddenlyToday** [comment]
感谢作者的耐心解答～

**Comment by suddenlyToday** [comment]
多谢🙏
